### ISSUE TITLE
Dataset Experiment

### ISSUE THREAD

**Issue by hamza13-12** [gifale95/eeg_encoding#4]
Hi. I would like to replicate the experiment that was used in the creation of this dataset. How can I perform this? Any pointers would be greatly appreciated. Is there an executable file that I have to run? If I have to clone your github, please share some pointers on how to run the data collection scripts. Thank you very much!

**Comment by hamza13-12** [comment]
Thank you for your response @gifale95. I have been working with your dataset for over a year now and would like to set up a very short call with you to get some pointers on the work I have been doing. Would this be a possibility?

**Comment by gifale95** [comment]
Your're welcome! Is there anything else or can I close the current Issue? As for the call, can we talk about that over email?
